[package]
name = "snif-common"
version.workspace = true
edition.workspace = true

[features]
default = []
user = ["aya", "http-collator"]

[dependencies]
aya = { workspace = true, optional = true }
http-collator = { path = "../../h2session/crates/http-collator", optional = true }
